//! Atomic state-write transaction (spec §7.2 step 14e).
//!
//! Bundles boxpilot.toml + controller-name + install-state.json +
//! cores/current symlink updates so any mid-crash interleaving leaves a
//! consistent or self-recoverable state.

use crate::dispatch::ControllerWrites;
use crate::paths::Paths;
use boxpilot_ipc::{BoxpilotConfig, CoreState, HelperError, HelperResult, InstallState};
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub struct ActiveFields {
    pub release_id: String,
    pub profile_id: String,
    pub profile_name: Option<String>,
    pub profile_sha256: String,
    pub activated_at: String,
}

#[derive(Debug, Clone)]
pub struct PreviousFields {
    pub release_id: String,
    pub profile_id: String,
    pub profile_sha256: String,
    pub activated_at: String,
}

#[derive(Debug, Clone, Default)]
pub struct TomlUpdates {
    pub core_path: Option<String>,
    pub core_state: Option<CoreState>,
    pub active: Option<ActiveFields>,
    pub previous: Option<PreviousFields>,
}

pub struct StateCommit {
    pub paths: Paths,
    pub toml_updates: TomlUpdates,
    pub controller: Option<ControllerWrites>,
    pub install_state: InstallState,
    pub current_symlink_target: Option<PathBuf>,
}

/// Render the polkit drop-in body. Username is JSON-escaped so a hostile
/// (or just unusual) username cannot inject additional polkit JS.
pub fn render_polkit_dropin(username: &str) -> String {
    // serde_json::to_string adds the surrounding quotes and escapes \ and ".
    let escaped = serde_json::to_string(username).expect("string serializes");
    format!(
        "// Generated by boxpilotd alongside /etc/boxpilot/controller-name.\n\
         // Do not edit — it is overwritten on every controller claim/transfer.\n\
         var BOXPILOT_CONTROLLER = {escaped};\n"
    )
}

/// Backfill `/etc/polkit-1/rules.d/48-boxpilot-controller.rules` from the
/// `controller_uid` recorded in `boxpilot.toml` when the drop-in is missing
/// — e.g. an in-place upgrade from a build that didn't write the drop-in.
/// Plan #1/#2 daemons claimed the controller without writing the drop-in;
/// without this backfill the controller would silently lose the reduced-
/// prompt auth tier the polkit JS rule grants when the global is set.
///
/// Returns `true` when a write happened, `false` for any of the legitimate
/// no-op cases (drop-in already present, no toml, no controller_uid, uid
/// not resolvable). Errors are reserved for filesystem/parse failures.
pub async fn backfill_polkit_dropin(
    paths: &Paths,
    user_lookup: &dyn crate::controller::UserLookup,
) -> HelperResult<bool> {
    let dropin_path = paths.polkit_controller_dropin_path();
    if dropin_path.exists() {
        return Ok(false);
    }
    let toml_path = paths.boxpilot_toml();
    let text = match tokio::fs::read_to_string(&toml_path).await {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(e) => {
            return Err(HelperError::Ipc {
                message: format!("read toml for backfill: {e}"),
            })
        }
    };
    let cfg = BoxpilotConfig::parse(&text)?;
    let Some(uid) = cfg.controller_uid else {
        return Ok(false);
    };
    let Some(username) = user_lookup.lookup_username(uid) else {
        return Ok(false);
    };
    if let Some(parent) = dropin_path.parent() {
        tokio::fs::create_dir_all(parent)
            .await
            .map_err(|e| HelperError::Ipc {
                message: format!("mkdir polkit rules.d for backfill: {e}"),
            })?;
    }
    tokio::fs::write(&dropin_path, render_polkit_dropin(&username))
        .await
        .map_err(|e| HelperError::Ipc {
            message: format!("write polkit drop-in for backfill: {e}"),
        })?;
    Ok(true)
}

impl StateCommit {
    pub async fn apply(self) -> HelperResult<()> {
        // 1. Stage all .new files.
        let install_state_path = self.paths.install_state_json();
        let toml_path = self.paths.boxpilot_toml();
        let controller_name_path = self.paths.controller_name_file();
        let current_symlink = self.paths.cores_current_symlink();

        // 1a. install-state.json.new
        let install_state_tmp = install_state_path.with_extension("json.new");
        if let Some(parent) = install_state_path.parent() {
            tokio::fs::create_dir_all(parent)
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("mkdir install-state parent: {e}"),
                })?;
        }
        // 1a (revised). If the caller passed an empty install_state and a
        // non-empty one is already on disk, preserve it — we're not changing
        // the cores ledger here. (Triggered by service.install_managed,
        // which only writes controller-name + boxpilot.toml + polkit drop-in.)
        let install_state_to_write =
            if self.install_state == InstallState::empty() && install_state_path.exists() {
                crate::core::state::read_state(&install_state_path).await?
            } else {
                self.install_state.clone()
            };
        tokio::fs::write(&install_state_tmp, install_state_to_write.to_json())
            .await
            .map_err(|e| HelperError::Ipc {
                message: format!("stage install-state: {e}"),
            })?;
        fsync_path(&install_state_tmp).await?;

        // 1b. current.new (if changing)
        let current_tmp = if let Some(target) = &self.current_symlink_target {
            if let Some(parent) = current_symlink.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|e| HelperError::Ipc {
                        message: format!("mkdir cores parent: {e}"),
                    })?;
            }
            let tmp = current_symlink.with_extension("new");
            // Best-effort cleanup of leftover .new from a prior crash.
            let _ = tokio::fs::remove_file(&tmp).await;
            // tokio::fs has no symlink helper; defer to std for the create.
            std::os::unix::fs::symlink(target, &tmp).map_err(|e| HelperError::Ipc {
                message: format!("stage current symlink: {e}"),
            })?;
            Some(tmp)
        } else {
            None
        };

        // 1c. controller-name.new
        let controller_name_tmp = if let Some(c) = &self.controller {
            if let Some(parent) = controller_name_path.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|e| HelperError::Ipc {
                        message: format!("mkdir etc parent: {e}"),
                    })?;
            }
            let tmp = controller_name_path.with_extension("name.new");
            tokio::fs::write(&tmp, format!("{}\n", c.username))
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("stage controller-name: {e}"),
                })?;
            fsync_path(&tmp).await?;
            Some(tmp)
        } else {
            None
        };

        // 1c'. polkit-controller-dropin.rules.new (only when claiming controller)
        let polkit_dropin_tmp = if let Some(c) = &self.controller {
            let dropin_path = self.paths.polkit_controller_dropin_path();
            if let Some(parent) = dropin_path.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|e| HelperError::Ipc {
                        message: format!("mkdir polkit rules.d parent: {e}"),
                    })?;
            }
            let tmp = dropin_path.with_extension("rules.new");
            tokio::fs::write(&tmp, render_polkit_dropin(&c.username))
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("stage polkit drop-in: {e}"),
                })?;
            fsync_path(&tmp).await?;
            Some((tmp, dropin_path))
        } else {
            None
        };

        // 1d. boxpilot.toml.new
        let mut cfg = match tokio::fs::read_to_string(&toml_path).await {
            Ok(text) => BoxpilotConfig::parse(&text)?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => BoxpilotConfig {
                schema_version: boxpilot_ipc::CURRENT_SCHEMA_VERSION,
                target_service: "boxpilot-sing-box.service".into(),
                core_path: None,
                core_state: None,
                controller_uid: None,
                active_profile_id: None,
                active_profile_name: None,
                active_profile_sha256: None,
                active_release_id: None,
                activated_at: None,
                previous_release_id: None,
                previous_profile_id: None,
                previous_profile_sha256: None,
                previous_activated_at: None,
            },
            Err(e) => {
                return Err(HelperError::Ipc {
                    message: format!("read toml: {e}"),
                })
            }
        };
        if let Some(p) = self.toml_updates.core_path {
            cfg.core_path = Some(p);
        }
        if let Some(s) = self.toml_updates.core_state {
            cfg.core_state = Some(s);
        }
        if let Some(c) = &self.controller {
            cfg.controller_uid = Some(c.uid);
        }
        if let Some(active) = &self.toml_updates.active {
            cfg.active_release_id = Some(active.release_id.clone());
            cfg.active_profile_id = Some(active.profile_id.clone());
            cfg.active_profile_name = active.profile_name.clone();
            cfg.active_profile_sha256 = Some(active.profile_sha256.clone());
            cfg.activated_at = Some(active.activated_at.clone());
        }
        if let Some(prev) = &self.toml_updates.previous {
            cfg.previous_release_id = Some(prev.release_id.clone());
            cfg.previous_profile_id = Some(prev.profile_id.clone());
            cfg.previous_profile_sha256 = Some(prev.profile_sha256.clone());
            cfg.previous_activated_at = Some(prev.activated_at.clone());
        }
        let toml_tmp = toml_path.with_extension("toml.new");
        if let Some(parent) = toml_path.parent() {
            tokio::fs::create_dir_all(parent)
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("mkdir toml parent: {e}"),
                })?;
        }
        tokio::fs::write(&toml_tmp, cfg.to_toml())
            .await
            .map_err(|e| HelperError::Ipc {
                message: format!("stage toml: {e}"),
            })?;
        fsync_path(&toml_tmp).await?;

        // 2. Commit in spec §7.2 step 14e order.
        // 2a. install-state.json
        tokio::fs::rename(&install_state_tmp, &install_state_path)
            .await
            .map_err(|e| HelperError::Ipc {
                message: format!("rename install-state: {e}"),
            })?;
        // 2b. current
        if let Some(tmp) = current_tmp {
            tokio::fs::rename(&tmp, &current_symlink)
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("rename current: {e}"),
                })?;
        }
        // 2c. controller-name
        if let Some(tmp) = controller_name_tmp {
            tokio::fs::rename(&tmp, &controller_name_path)
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("rename controller-name: {e}"),
                })?;
        }
        // 2c'. polkit drop-in (right after controller-name so the two are
        // visible as a single unit to anyone reading /etc).
        if let Some((tmp, final_path)) = polkit_dropin_tmp {
            tokio::fs::rename(&tmp, &final_path)
                .await
                .map_err(|e| HelperError::Ipc {
                    message: format!("rename polkit drop-in: {e}"),
                })?;
        }
        // 2d. boxpilot.toml
        tokio::fs::rename(&toml_tmp, &toml_path)
            .await
            .map_err(|e| HelperError::Ipc {
                message: format!("rename toml: {e}"),
            })?;

        Ok(())
    }
}

/// Open and fsync a path so the bytes hit disk before a rename(2) makes
/// the new inode visible. Required so a crash mid-commit cannot leave a
/// renamed file pointing at zero/truncated content (spec §7.2 step 14e).
async fn fsync_path(path: &std::path::Path) -> HelperResult<()> {
    let f = tokio::fs::OpenOptions::new()
        .read(true)
        .open(path)
        .await
        .map_err(|e| HelperError::Ipc {
            message: format!("open for fsync {path:?}: {e}"),
        })?;
    f.sync_all().await.map_err(|e| HelperError::Ipc {
        message: format!("fsync {path:?}: {e}"),
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dispatch::ControllerWrites;
    use tempfile::tempdir;

    /// Add a few helpers to Paths in test context.
    fn paths_for(tmp: &tempfile::TempDir) -> Paths {
        std::fs::create_dir_all(tmp.path().join("etc/boxpilot")).unwrap();
        std::fs::create_dir_all(tmp.path().join("var/lib/boxpilot/cores")).unwrap();
        Paths::with_root(tmp.path())
    }

    #[tokio::test]
    async fn apply_writes_install_state_and_toml() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        let mut state = InstallState::empty();
        state.current_managed_core = Some("1.10.0".into());
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates {
                core_path: Some("/var/lib/boxpilot/cores/current/sing-box".into()),
                core_state: Some(CoreState::ManagedInstalled),
                ..TomlUpdates::default()
            },
            controller: None,
            install_state: state.clone(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();
        let saved = tokio::fs::read_to_string(paths.install_state_json())
            .await
            .unwrap();
        assert!(saved.contains(r#""current_managed_core": "1.10.0""#));
        let toml = tokio::fs::read_to_string(paths.boxpilot_toml())
            .await
            .unwrap();
        assert!(toml.contains("core_state = \"managed-installed\""));
    }

    #[tokio::test]
    async fn apply_writes_controller_name_when_claiming() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates::default(),
            controller: Some(ControllerWrites {
                uid: 1000,
                username: "alice".into(),
            }),
            install_state: InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();
        let name = tokio::fs::read_to_string(paths.controller_name_file())
            .await
            .unwrap();
        assert_eq!(name.trim(), "alice");
        let toml = tokio::fs::read_to_string(paths.boxpilot_toml())
            .await
            .unwrap();
        assert!(toml.contains("controller_uid = 1000"));
    }

    #[tokio::test]
    async fn apply_writes_polkit_dropin_when_claiming_controller() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates::default(),
            controller: Some(ControllerWrites {
                uid: 1000,
                username: "alice".into(),
            }),
            install_state: InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();
        let dropin = tokio::fs::read_to_string(paths.polkit_controller_dropin_path())
            .await
            .unwrap();
        assert!(dropin.contains("var BOXPILOT_CONTROLLER = \"alice\";"));
    }

    #[tokio::test]
    async fn apply_does_not_write_polkit_dropin_when_not_claiming() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates {
                core_path: Some("/x".into()),
                core_state: Some(CoreState::ManagedInstalled),
                ..TomlUpdates::default()
            },
            controller: None,
            install_state: InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();
        assert!(!paths.polkit_controller_dropin_path().exists());
    }

    #[tokio::test]
    async fn apply_escapes_quotes_and_backslashes_in_username() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates::default(),
            controller: Some(ControllerWrites {
                uid: 1000,
                username: r#"a"\b"#.into(),
            }),
            install_state: InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();
        let dropin = tokio::fs::read_to_string(paths.polkit_controller_dropin_path())
            .await
            .unwrap();
        // Backslash and double-quote are escaped; no raw injection vector.
        assert!(dropin.contains(r#"var BOXPILOT_CONTROLLER = "a\"\\b";"#));
    }

    #[tokio::test]
    async fn apply_preserves_existing_install_state_when_caller_passes_empty() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        // Pre-seed install-state.json with a real ledger (1 managed core).
        let mut seeded = InstallState::empty();
        seeded.managed_cores.push(boxpilot_ipc::ManagedCoreEntry {
            version: "1.10.0".into(),
            path: "/var/lib/boxpilot/cores/1.10.0/sing-box".into(),
            sha256: "deadbeef".into(),
            installed_at: "2026-04-29T00:00:00Z".into(),
            source: "github-sagernet".into(),
        });
        seeded.current_managed_core = Some("1.10.0".into());
        std::fs::create_dir_all(paths.install_state_json().parent().unwrap()).unwrap();
        std::fs::write(paths.install_state_json(), seeded.to_json()).unwrap();

        // Now run a StateCommit with an empty install_state (as
        // service.install_managed would). Existing ledger must survive.
        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates::default(),
            controller: Some(ControllerWrites {
                uid: 1000,
                username: "alice".into(),
            }),
            install_state: InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();

        let after = crate::core::state::read_state(&paths.install_state_json())
            .await
            .unwrap();
        assert_eq!(after.managed_cores.len(), 1);
        assert_eq!(after.current_managed_core.as_deref(), Some("1.10.0"));
    }

    #[tokio::test]
    async fn backfill_writes_dropin_when_missing_and_controller_known() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        std::fs::write(
            paths.boxpilot_toml(),
            "schema_version = 1\ncontroller_uid = 1000\n",
        )
        .unwrap();
        let lookup = crate::controller::testing::Fixed::new(&[(1000, "alice")]);
        let wrote = backfill_polkit_dropin(&paths, &lookup).await.unwrap();
        assert!(wrote);
        let body = tokio::fs::read_to_string(paths.polkit_controller_dropin_path())
            .await
            .unwrap();
        assert!(body.contains(r#"var BOXPILOT_CONTROLLER = "alice";"#));
    }

    #[tokio::test]
    async fn backfill_is_noop_when_dropin_already_present() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        std::fs::write(
            paths.boxpilot_toml(),
            "schema_version = 1\ncontroller_uid = 1000\n",
        )
        .unwrap();
        let dropin = paths.polkit_controller_dropin_path();
        std::fs::create_dir_all(dropin.parent().unwrap()).unwrap();
        std::fs::write(&dropin, "// pre-existing\n").unwrap();
        let lookup = crate::controller::testing::Fixed::new(&[(1000, "alice")]);
        let wrote = backfill_polkit_dropin(&paths, &lookup).await.unwrap();
        assert!(!wrote);
        // Existing file untouched.
        let body = std::fs::read_to_string(&dropin).unwrap();
        assert_eq!(body, "// pre-existing\n");
    }

    #[tokio::test]
    async fn backfill_is_noop_when_no_controller_uid() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        std::fs::write(paths.boxpilot_toml(), "schema_version = 1\n").unwrap();
        let lookup = crate::controller::testing::Fixed::new(&[]);
        let wrote = backfill_polkit_dropin(&paths, &lookup).await.unwrap();
        assert!(!wrote);
        assert!(!paths.polkit_controller_dropin_path().exists());
    }

    #[tokio::test]
    async fn backfill_is_noop_when_uid_not_resolvable() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        std::fs::write(
            paths.boxpilot_toml(),
            "schema_version = 1\ncontroller_uid = 1000\n",
        )
        .unwrap();
        let lookup = crate::controller::testing::Fixed::new(&[]); // 1000 not in map
        let wrote = backfill_polkit_dropin(&paths, &lookup).await.unwrap();
        assert!(!wrote);
        assert!(!paths.polkit_controller_dropin_path().exists());
    }

    #[tokio::test]
    async fn backfill_is_noop_when_no_toml_at_all() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        // No boxpilot.toml — fresh-install path.
        let lookup = crate::controller::testing::Fixed::new(&[(1000, "alice")]);
        let wrote = backfill_polkit_dropin(&paths, &lookup).await.unwrap();
        assert!(!wrote);
        assert!(!paths.polkit_controller_dropin_path().exists());
    }

    #[tokio::test]
    async fn state_commit_writes_active_and_previous_fields() {
        let tmp = tempdir().unwrap();
        let paths = paths_for(&tmp);
        std::fs::write(
            paths.boxpilot_toml(),
            "schema_version = 1\ncontroller_uid = 1000\nactive_release_id = \"old-id\"\nactive_profile_id = \"old-p\"\nactive_profile_sha256 = \"old-sha\"\nactivated_at = \"2026-04-29T00:00:00-07:00\"\n",
        )
        .unwrap();

        let commit = StateCommit {
            paths: paths.clone(),
            toml_updates: TomlUpdates {
                core_path: None,
                core_state: None,
                active: Some(ActiveFields {
                    release_id: "new-id".into(),
                    profile_id: "new-p".into(),
                    profile_name: Some("New".into()),
                    profile_sha256: "new-sha".into(),
                    activated_at: "2026-04-30T00:00:00-07:00".into(),
                }),
                previous: Some(PreviousFields {
                    release_id: "old-id".into(),
                    profile_id: "old-p".into(),
                    profile_sha256: "old-sha".into(),
                    activated_at: "2026-04-29T00:00:00-07:00".into(),
                }),
            },
            controller: None,
            install_state: boxpilot_ipc::InstallState::empty(),
            current_symlink_target: None,
        };
        commit.apply().await.unwrap();

        let cfg = boxpilot_ipc::BoxpilotConfig::parse(
            &tokio::fs::read_to_string(paths.boxpilot_toml())
                .await
                .unwrap(),
        )
        .unwrap();
        assert_eq!(cfg.active_release_id.as_deref(), Some("new-id"));
        assert_eq!(cfg.active_profile_id.as_deref(), Some("new-p"));
        assert_eq!(cfg.active_profile_name.as_deref(), Some("New"));
        assert_eq!(cfg.active_profile_sha256.as_deref(), Some("new-sha"));
        assert_eq!(
            cfg.activated_at.as_deref(),
            Some("2026-04-30T00:00:00-07:00")
        );
        assert_eq!(cfg.previous_release_id.as_deref(), Some("old-id"));
        assert_eq!(cfg.previous_profile_id.as_deref(), Some("old-p"));
        assert_eq!(cfg.previous_profile_sha256.as_deref(), Some("old-sha"));
        assert_eq!(
            cfg.previous_activated_at.as_deref(),
            Some("2026-04-29T00:00:00-07:00")
        );
    }
}
